import json
import os
from datetime import date, datetime

import duckdb
import pytest

from ingest import cli, metrics


@pytest.fixture
def env(tmp_path, tiny_sample, monkeypatch):
    for name in ("WAREHOUSE", "OBSERVABILITY_DB_URL", "DUCKDB_PATH"):
        monkeypatch.delenv(name, raising=False)
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "data"))
    monkeypatch.setenv("SAMPLE_DIR", str(tiny_sample))
    # Never run a real Synthea in unit tests, even if .cache/ holds the jar.
    monkeypatch.setenv("SYNTHEA_JAR", str(tmp_path / "missing.jar"))
    return tmp_path / "data"


def raw_count(data_dir, table):
    with duckdb.connect(str(data_dir / "warehouse.duckdb")) as con:
        return con.execute(f"select count(*) from raw.{table}").fetchone()[0]


def test_generate_then_load_on_duckdb_is_idempotent(env):
    args = ["--batch-date", "2026-01-01"]
    assert cli.main(["generate", *args, "--use-sample"]) == 0
    assert cli.main(["load", *args]) == 0
    first = raw_count(env, "patients")
    assert 0 < first <= 10
    assert cli.main(["load", *args]) == 0
    assert raw_count(env, "patients") == first


def test_generate_without_jar_falls_back_to_sample(env):
    assert cli.main(["generate", "--batch-date", "2026-01-01"]) == 0
    assert (env / "batches" / "20260101" / "patients.csv").exists()


def raw_batches(data_dir, table="patients"):
    with duckdb.connect(str(data_dir / "warehouse.duckdb")) as con:
        rows = con.execute(f"select distinct _BATCH_ID from raw.{table} order by 1").fetchall()
    return [r[0] for r in rows]


def generate_and_load(day):
    assert cli.main(["generate", "--batch-date", day, "--use-sample"]) == 0
    return cli.main(["load", "--batch-date", day])


def test_load_prunes_raw_older_than_30_days_after_success(env):
    for day in ("2026-01-01", "2026-01-16", "2026-01-31"):
        assert generate_and_load(day) == 0
    assert raw_batches(env) == ["20260101", "20260116", "20260131"]  # exactly 30 days: kept
    assert generate_and_load("2026-02-15") == 0
    for table in ("patients", "payers", "claims_transactions"):
        assert raw_batches(env, table) == ["20260116", "20260131", "20260215"]


def test_load_does_not_prune_raw_when_a_table_fails(env):
    assert generate_and_load("2026-01-01") == 0
    assert cli.main(["generate", "--batch-date", "2026-03-01", "--use-sample"]) == 0
    (env / "batches" / "20260301" / "medications.csv").unlink()
    assert cli.main(["load", "--batch-date", "2026-03-01"]) == 1
    assert raw_batches(env) == ["20260101", "20260301"]


def test_generate_keeps_the_three_newest_batch_dirs(env):
    batches = env / "batches"
    (batches / ".synthea-20251231").mkdir(parents=True)
    for day in ("2026-01-01", "2026-01-02", "2026-01-03", "2026-01-04"):
        assert cli.main(["generate", "--batch-date", day, "--use-sample"]) == 0
    assert sorted(p.name for p in batches.iterdir()) == ["20260102", "20260103", "20260104"]


def test_generate_writes_manifest(env):
    assert (
        cli.main(["generate", "--run-id", "r1", "--batch-date", "2026-01-01", "--use-sample"]) == 0
    )
    manifest = json.loads((env / "batches" / "20260101" / "_manifest.json").read_text())
    assert manifest["run_id"] == "r1"
    assert manifest["source"] == "sample"
    assert datetime.fromisoformat(manifest["generated_at"]).tzinfo is not None


def test_load_accepts_batch_from_the_same_run(env):
    run = ["--run-id", "r1", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["load", *run]) == 0


def test_load_rejects_batch_generated_by_another_run(env, caplog):
    assert (
        cli.main(["generate", "--run-id", "r1", "--batch-date", "2026-01-01", "--use-sample"]) == 0
    )
    assert cli.main(["load", "--run-id", "r2", "--batch-date", "2026-01-01"]) == 1
    assert "batch 20260101 was generated by run r1; re-run generate for this run" in caplog.text
    assert not (env / "warehouse.duckdb").exists()  # refused before opening the warehouse


def test_load_without_run_ids_skips_the_manifest_check(env):
    assert cli.main(["generate", "--batch-date", "2026-01-01", "--use-sample"]) == 0
    assert cli.main(["load", "--run-id", "r2", "--batch-date", "2026-01-01"]) == 0
    assert (
        cli.main(["generate", "--run-id", "r1", "--batch-date", "2026-01-02", "--use-sample"]) == 0
    )
    assert cli.main(["load", "--batch-date", "2026-01-02"]) == 0


def test_load_fails_when_batch_is_missing(env):
    assert cli.main(["load", "--batch-date", "2026-02-02"]) == 1


def test_apply_security_is_a_noop_on_duckdb(env):
    assert cli.main(["apply-security", "--batch-date", "2026-01-01"]) == 0


def test_bad_config_exits_2(env, monkeypatch):
    monkeypatch.setenv("WAREHOUSE", "oracle")
    assert cli.main(["load", "--batch-date", "2026-01-01"]) == 2


def test_snowflake_without_credentials_fails_fast_in_generate(env, monkeypatch):
    monkeypatch.setenv("WAREHOUSE", "snowflake")
    assert cli.main(["generate", "--batch-date", "2026-01-01", "--use-sample"]) == 2
    assert not (env / "batches").exists()  # failed before doing any work


def test_record_metrics_without_db_is_a_noop(env):
    assert cli.main(["record-metrics", "--batch-date", "2026-01-01"]) == 0


@pytest.fixture
def pg_url(monkeypatch):
    url = os.environ.get("TEST_POSTGRES_URL")
    if not url:
        pytest.skip("set TEST_POSTGRES_URL to a throwaway database (name must contain 'test')")
    import psycopg

    with psycopg.connect(url, autocommit=True) as c:
        c.execute("drop schema if exists observability cascade")
    monkeypatch.setenv("OBSERVABILITY_DB_URL", url)
    return url


def test_record_metrics_returns_1_when_pipeline_failed(env, pg_url):
    run = ["--run-id", "r1", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["record-metrics", *run]) == 1  # load/security/dbt never ran
    with metrics.connect(pg_url) as conn:
        assert metrics.task_states(conn, "r1")["load_raw"] == "upstream_failed"
        assert conn.execute("select status from observability.pipeline_runs").fetchone() == (
            "failed",
        )


def test_snowflake_config_error_is_recorded_as_failed_generate(env, pg_url, monkeypatch):
    run = ["--run-id", "r1", "--batch-date", "2026-01-01"]
    monkeypatch.setenv("WAREHOUSE", "snowflake")
    assert cli.main(["generate", *run, "--use-sample"]) == 2
    with metrics.connect(pg_url) as conn:
        assert metrics.task_states(conn, "r1") == {"generate": "failed"}


def test_record_metrics_finalizes_even_when_kpis_fail(env, pg_url):
    with metrics.connect(pg_url) as conn:
        for t in cli.PIPELINE_TASKS:
            metrics.record_task(conn, "r2", t, "success", None, 1.0)
    # dbt_build "succeeded" but no marts exist, so KPI capture fails; the run must still finalize.
    assert cli.main(["record-metrics", "--run-id", "r2", "--batch-date", "2026-01-01"]) == 0
    with metrics.connect(pg_url) as conn:
        row = conn.execute(
            "select status, batch_date from observability.pipeline_runs where run_id = 'r2'"
        ).fetchone()
    assert row == ("success", date(2026, 1, 1))


def test_load_records_stats_per_table(env, pg_url):
    run = ["--run-id", "r3", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["load", *run]) == 0
    with metrics.connect(pg_url) as conn:
        (n,) = conn.execute(
            "select count(*) from observability.load_stats "
            "where run_id = 'r3' and status = 'success'"
        ).fetchone()
        states = metrics.task_states(conn, "r3")
    assert n == 8
    assert states == {"generate": "success", "load_raw": "success"}


def test_raw_prune_error_fails_load_after_stats_are_recorded(env, pg_url, monkeypatch):
    def boom(loader, before_batch_id):
        raise RuntimeError("prune failed")

    monkeypatch.setattr("ingest.loaders.prune_raw", boom)
    run = ["--run-id", "r5", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["load", *run]) == 1
    with metrics.connect(pg_url) as conn:
        (n,) = conn.execute(
            "select count(*) from observability.load_stats "
            "where run_id = 'r5' and status = 'success'"
        ).fetchone()
        states = metrics.task_states(conn, "r5")
    assert n == 8
    assert states["load_raw"] == "failed"


DOWN_DB = "postgresql://nobody:nothing@127.0.0.1:1/nowhere?connect_timeout=2"


def test_generate_and_load_succeed_when_metrics_db_is_down(env, monkeypatch):
    monkeypatch.setenv("OBSERVABILITY_DB_URL", DOWN_DB)
    run = ["--run-id", "r9", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["load", *run]) == 0
    assert raw_count(env, "patients") > 0


def _fake_dbt(monkeypatch, rcs):
    import shutil
    from pathlib import Path

    def fake(settings, batch_id, target_path):
        target_path.mkdir(parents=True, exist_ok=True)
        fixture = Path(__file__).parent / "fixtures" / "run_results.json"
        shutil.copy(fixture, target_path / "run_results.json")
        return rcs

    monkeypatch.setattr("ingest.dbt_runner.run_dbt", fake)


def test_dbt_build_succeeds_when_metrics_db_is_down(env, monkeypatch):
    monkeypatch.setenv("OBSERVABILITY_DB_URL", DOWN_DB)
    _fake_dbt(monkeypatch, [0, 0])
    assert cli.main(["dbt-build", "--run-id", "r9", "--batch-date", "2026-01-01"]) == 0


def test_dbt_build_still_fails_on_nonzero_exit_when_metrics_db_is_down(env, monkeypatch):
    monkeypatch.setenv("OBSERVABILITY_DB_URL", DOWN_DB)
    _fake_dbt(monkeypatch, [0, 1])
    assert cli.main(["dbt-build", "--run-id", "r9", "--batch-date", "2026-01-01"]) == 1


def test_dbt_build_ignores_stale_run_results(env, monkeypatch):
    from ingest import dbt_runner
    from ingest.config import load_settings

    stale = dbt_runner.target_path_for(load_settings(), "r8") / "run_results.json"
    stale.parent.mkdir(parents=True, exist_ok=True)
    stale.write_text("{}")
    seen = {}

    def fake(settings, batch_id, target_path):
        seen["existed"] = (target_path / "run_results.json").exists()
        return [0, 0]

    monkeypatch.setattr("ingest.dbt_runner.run_dbt", fake)
    try:
        assert cli.main(["dbt-build", "--run-id", "r8", "--batch-date", "2026-01-01"]) == 0
    finally:
        stale.unlink(missing_ok=True)
    assert seen["existed"] is False


def test_record_metrics_finalizes_when_record_kpis_aborts_the_transaction(env, pg_url, monkeypatch):
    with metrics.connect(pg_url) as conn:
        for t in cli.PIPELINE_TASKS:
            metrics.record_task(conn, "r4", t, "success", None, 1.0)

    def boom(conn, run_id, values):
        conn.execute("select 1/0")

    monkeypatch.setattr("ingest.kpis.marts_batch_id", lambda query: "20260101")
    monkeypatch.setattr("ingest.kpis.compute_kpis", lambda query: [("x", 1.0)])
    monkeypatch.setattr("ingest.metrics.record_kpis", boom)
    assert cli.main(["record-metrics", "--run-id", "r4", "--batch-date", "2026-01-01"]) == 0
    with metrics.connect(pg_url) as conn:
        row = conn.execute(
            "select status from observability.pipeline_runs where run_id = 'r4'"
        ).fetchone()
    assert row == ("success",)


def _all_pipeline_tasks_succeeded(url, run_id):
    with metrics.connect(url) as conn:
        for t in cli.PIPELINE_TASKS:
            metrics.record_task(conn, run_id, t, "success", None, 1.0)


def _kpi_count(url, run_id):
    with metrics.connect(url) as conn:
        return conn.execute(
            "select count(*) from observability.kpi_snapshots where run_id = %s", (run_id,)
        ).fetchone()[0]


def test_record_metrics_skips_kpis_built_from_another_batch(env, pg_url, monkeypatch):
    _all_pipeline_tasks_succeeded(pg_url, "r5")
    # Another run rebuilt the marts for a different day before this run captured its KPIs.
    monkeypatch.setattr("ingest.kpis.marts_batch_id", lambda query: "20251231")
    monkeypatch.setattr("ingest.kpis.compute_kpis", lambda query: [("x", 1.0)])
    assert cli.main(["record-metrics", "--run-id", "r5", "--batch-date", "2026-01-01"]) == 0
    assert _kpi_count(pg_url, "r5") == 0


def test_record_metrics_captures_kpis_for_its_own_batch(env, pg_url, monkeypatch):
    _all_pipeline_tasks_succeeded(pg_url, "r6")
    monkeypatch.setattr("ingest.kpis.marts_batch_id", lambda query: "20260101")
    monkeypatch.setattr("ingest.kpis.compute_kpis", lambda query: [("x", 1.0)])
    assert cli.main(["record-metrics", "--run-id", "r6", "--batch-date", "2026-01-01"]) == 0
    assert _kpi_count(pg_url, "r6") == 1


def test_generate_records_the_data_source(env, pg_url):
    run = ["--run-id", "r7", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    assert cli.main(["generate", "--run-id", "r8", "--batch-date", "2026-01-02"]) == 0  # no jar
    with metrics.connect(pg_url) as conn:
        rows = dict(
            conn.execute("select run_id, data_source from observability.pipeline_runs").fetchall()
        )
    assert rows == {"r7": "sample", "r8": "sample_fallback"}


def batch_csv(data_dir, table, day="20260101"):
    return data_dir / "batches" / day / f"{table}.csv"


def duplicate_first_row(path):
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    path.write_text("".join([*lines, lines[1]]), encoding="utf-8")


def replace_in_csv(path, old, new):
    path.write_text(path.read_text(encoding="utf-8").replace(old, new), encoding="utf-8")


def test_check_contracts_passes_on_a_generated_batch(env):
    args = ["--batch-date", "2026-01-01"]
    assert cli.main(["generate", *args, "--use-sample"]) == 0
    assert cli.main(["check-contracts", *args]) == 0


def test_check_contracts_fails_on_an_error_rule(env, caplog):
    args = ["--batch-date", "2026-01-01"]
    assert cli.main(["generate", *args, "--use-sample"]) == 0
    duplicate_first_row(batch_csv(env, "patients"))
    assert cli.main(["check-contracts", *args]) == 1
    assert "patients.ID unique" in caplog.text
    assert "1 error(s)" in caplog.text


def test_check_contracts_passes_with_only_warnings(env, caplog):
    args = ["--batch-date", "2026-01-01"]
    assert cli.main(["generate", *args, "--use-sample"]) == 0
    replace_in_csv(batch_csv(env, "encounters"), "ambulatory", "teleport")
    assert cli.main(["check-contracts", *args]) == 0
    assert "encounters.ENCOUNTERCLASS accepted_values" in caplog.text
    assert "teleport" in caplog.text  # not a pii column: examples are logged


def test_check_contracts_never_logs_pii_values(env, caplog):
    args = ["--batch-date", "2026-01-01"]
    assert cli.main(["generate", *args, "--use-sample"]) == 0
    path = batch_csv(env, "patients")
    first_id = path.read_text(encoding="utf-8").splitlines()[1].split(",")[0]
    duplicate_first_row(path)
    assert cli.main(["check-contracts", *args]) == 1
    assert "patients.ID unique" in caplog.text
    assert first_id not in caplog.text


def test_check_contracts_fails_when_the_batch_is_missing(env):
    assert cli.main(["check-contracts", "--batch-date", "2026-01-01"]) == 1


def test_check_contracts_records_every_rule_and_replaces_a_rerun(env, pg_url):
    run = ["--run-id", "r6", "--batch-date", "2026-01-01"]
    assert cli.main(["generate", *run, "--use-sample"]) == 0
    duplicate_first_row(batch_csv(env, "patients"))
    assert cli.main(["check-contracts", *run]) == 1
    assert cli.main(["check-contracts", *run]) == 1  # a retry must not duplicate rows
    with metrics.connect(pg_url) as conn:
        total, failing = conn.execute(
            "select count(*), count(*) filter (where failing_rows > 0) "
            "from observability.contract_results where run_id = 'r6'"
        ).fetchone()
        unique = conn.execute(
            "select severity, failing_rows, examples from observability.contract_results "
            "where run_id = 'r6' and table_name = 'patients' and column_name = 'ID' "
            "and rule = 'unique'"
        ).fetchone()
        states = metrics.task_states(conn, "r6")
    assert total > 100
    assert failing == 1
    assert unique == ("error", 2, [])  # pii: count only
    assert states["check_contracts"] == "failed"
