"""Pipeline commands. Airflow runs these as `python -m ingest.cli <command>`; so can you:

    uv run python -m ingest.cli generate --batch-date 2026-01-01 --use-sample
    uv run python -m ingest.cli load --batch-date 2026-01-01
    uv run python -m ingest.cli dbt-build --batch-date 2026-01-01

With --run-id and OBSERVABILITY_DB_URL set, each command records its own metrics.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

from ingest import dbt_runner, kpis, loaders, metrics, security, synthea
from ingest.config import ConfigError, Settings, load_settings

log = logging.getLogger("ingest.cli")

# Tasks whose success makes a run successful (record_metrics itself is the judge, not a member).
PIPELINE_TASKS = ("generate", "load_raw", "apply_security", "dbt_build")


def _metrics_on(args, settings: Settings) -> bool:
    return bool(args.run_id and settings.observability_db_url)


def _best_effort(what: str, fn) -> None:
    """Metrics are bookkeeping: a Postgres outage must never change a task's real result."""
    try:
        fn()
    except Exception:
        log.exception("could not record %s; continuing", what)


def _track(args, settings: Settings, task_id: str):
    return metrics.track_task(settings.observability_db_url, args.run_id, task_id)


def cmd_generate(args, settings: Settings) -> int:
    if settings.warehouse == "snowflake":
        # Fail fast, before minutes of Synthea, and record it so the run shows generate
        # as failed (not upstream_failed) on the dashboard.
        with _track(args, settings, "generate"):
            settings.require_snowflake()
    if _metrics_on(args, settings):

        def start_run():
            with metrics.connect(settings.observability_db_url) as conn:
                metrics.start_pipeline_run(conn, args.run_id, args.batch_date, settings.warehouse)

        _best_effort("pipeline run start", start_run)
    batch_id = synthea.batch_id_for(args.batch_date)
    dest = synthea.batch_dir(settings.data_dir, batch_id)
    with _track(args, settings, "generate"):
        # Keep 2 old batches, so with this one there are 3 (a real Synthea day is ~1 GB).
        pruned = synthea.prune_batches(settings.data_dir, keep=2)
        if pruned:
            log.info("pruned old batch directories: %s", ", ".join(pruned))
        source = synthea.generate(
            dest,
            args.batch_date,
            sample_dir=settings.sample_dir,
            jar=settings.synthea_jar,
            population=settings.synthea_population,
            use_sample=args.use_sample,
        )
        # Records which run wrote the batch, so load can refuse another run's data.
        manifest = {
            "run_id": args.run_id,
            "source": source,
            "generated_at": datetime.now(UTC).isoformat(),
        }
        (dest / synthea.MANIFEST).write_text(json.dumps(manifest, indent=2))
    log.info("batch %s written to %s (source: %s)", batch_id, dest, source)
    return 0


def _check_manifest(args, batch_id: str, directory: Path) -> None:
    path = directory / synthea.MANIFEST
    manifest = json.loads(path.read_text()) if path.is_file() else {}
    owner = manifest.get("run_id")
    if args.run_id and owner and owner != args.run_id:
        raise RuntimeError(
            f"batch {batch_id} was generated by run {owner}; re-run generate for this run"
        )
    log.info("loading batch %s (source: %s)", batch_id, manifest.get("source", "unknown"))


def cmd_load(args, settings: Settings) -> int:
    batch_id = synthea.batch_id_for(args.batch_date)
    directory = synthea.batch_dir(settings.data_dir, batch_id)
    with _track(args, settings, "load_raw"):
        _check_manifest(args, batch_id, directory)
        loader = loaders.get_loader(settings, role="LOADER")
        try:
            results = loaders.load_all(loader, directory, batch_id)
            if _metrics_on(args, settings):

                def record_stats():
                    with metrics.connect(settings.observability_db_url) as conn:
                        metrics.record_load_stats(conn, args.run_id, results)

                _best_effort("load stats", record_stats)
            for r in results:
                log.info("%-20s %-8s rows=%s %s", r.table, r.status, r.rows_loaded, r.error or "")
            failed = [r.table for r in results if r.status != "success"]
            if failed:
                raise RuntimeError(f"load failed for tables: {', '.join(failed)}")
            # Retention runs only after a full success; unlike metrics, its errors fail the task.
            cutoff = args.batch_date - timedelta(days=loaders.RAW_RETENTION_DAYS)
            pruned = loaders.prune_raw(loader, synthea.batch_id_for(cutoff))
            log.info("RAW retention: deleted %d rows older than %s", sum(pruned.values()), cutoff)
        finally:
            loader.close()
    return 0


def cmd_apply_security(args, settings: Settings) -> int:
    with _track(args, settings, "apply_security"):
        if settings.warehouse != "snowflake":
            log.info(
                "WAREHOUSE=%s has no masking support; skipping (see README)", settings.warehouse
            )
            return 0
        conn = loaders.snowflake_connection(settings.require_snowflake(), role="PLATFORM_ADMIN")
        try:
            n = security.apply_security(conn, settings.snowflake_sql_dir)
        finally:
            conn.close()
        log.info("applied %d security statements", n)
    return 0


def cmd_dbt_build(args, settings: Settings) -> int:
    batch_id = synthea.batch_id_for(args.batch_date)
    target_path = dbt_runner.target_path_for(settings, args.run_id)
    with _track(args, settings, "dbt_build"):
        run_results = target_path / "run_results.json"
        run_results.unlink(missing_ok=True)  # never record a stale file from an earlier try
        freshness_rc, build_rc = dbt_runner.run_dbt(settings, batch_id, target_path)
        if _metrics_on(args, settings) and run_results.exists():

            def record_results():
                with metrics.connect(settings.observability_db_url) as conn:
                    metrics.record_dbt_results(
                        conn, args.run_id, metrics.parse_run_results(run_results)
                    )

            _best_effort("dbt results", record_results)
        if freshness_rc or build_rc:
            raise RuntimeError(f"dbt failed (freshness rc={freshness_rc}, build rc={build_rc})")
    return 0


def cmd_record_metrics(args, settings: Settings) -> int:
    if not _metrics_on(args, settings):
        log.info("no --run-id or OBSERVABILITY_DB_URL; nothing to record")
        return 0
    with metrics.connect(settings.observability_db_url) as conn:
        if metrics.task_states(conn, args.run_id).get("dbt_build") == "success":
            try:
                loader = loaders.get_loader(settings, role="TRANSFORMER")
                try:
                    values = kpis.compute_kpis(loader.query)
                finally:
                    loader.close()
                metrics.record_kpis(conn, args.run_id, values)
            except Exception:
                log.exception("KPI capture failed; still finalizing the run")
                conn.rollback()  # a failed write leaves the transaction aborted
        status = metrics.finalize_pipeline_run(
            conn, args.run_id, PIPELINE_TASKS, args.batch_date, settings.warehouse
        )
    log.info("run %s finished: %s", args.run_id, status)
    # Fail this task too, so Airflow's DAG run state matches the dashboard.
    return 0 if status == "success" else 1


COMMANDS = {
    "generate": cmd_generate,
    "load": cmd_load,
    "apply-security": cmd_apply_security,
    "dbt-build": cmd_dbt_build,
    "record-metrics": cmd_record_metrics,
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ingest.cli", description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    for name in COMMANDS:
        p = sub.add_parser(name)
        p.add_argument("--run-id", default=None, help="Airflow run_id; enables metrics")
        p.add_argument("--batch-date", type=date.fromisoformat, required=True)
        if name == "generate":
            p.add_argument("--use-sample", action="store_true", help="skip Synthea")
    return parser


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s"
    )
    args = build_parser().parse_args(argv)
    try:
        return COMMANDS[args.command](args, load_settings())
    except ConfigError as exc:
        log.error("configuration error: %s", exc)
        return 2
    except Exception:
        log.exception("%s failed", args.command)
        return 1


if __name__ == "__main__":
    sys.exit(main())
